const fs = require('node:fs');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const html = fs.readFileSync(process.argv[2] || 'index.html', 'utf8');
const script = html.match(/<script>([\s\S]*?)<\/script>/)[1];
new vm.Script(script);
const escapeFunction = script.slice(script.indexOf('function escapeHTML'), script.indexOf("function render"));
const context = vm.createContext({});
vm.runInContext(escapeFunction, context);
assert.equal(context.escapeHTML('<img src=x onerror="alert(1)">'), '&lt;img src=x onerror=&quot;alert(1)&quot;&gt;');
assert.equal(context.escapeHTML("Work & study's plan"), 'Work &amp; study&#39;s plan');
assert.ok(script.includes("escapeHTML(t[0])"));
assert.ok(!html.includes('chatgpt.com/api/library'));
assert.ok(!html.includes('href="https://dayflow-app.zerotech-limited.chatgpt.site"'));
const ids = new Set([...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]));
for (const [, id] of html.matchAll(/href="#([^"]+)"/g)) assert.ok(ids.has(id), 'Missing section: '+id);
const downloads = [...html.matchAll(/data-file="installer" href="([^"]+)"/g)].map(x=>x[1]);
assert.equal(downloads.length, 2);
assert.ok(downloads.every(x=>x==='https://github.com/Pronto4056/dayflow-desktop/releases/download/V1.0.0/DayFlow-Setup-1.0.0.exe'));
assert.ok(html.includes('7d35283ec269e7436a5c2ca72cb1533c60dad311f676d7fc49e6967e31b8af0d'));
assert.ok(html.includes('Illustrative demo'));
console.log('PASS: JavaScript syntax, HTML escaping, navigation targets, public installer URLs, checksum, demo labeling.');
console.log('Not covered: browser interaction, network downloads, desktop app workflows.');
